---
title: Compagnie Jtembrasse
timezone: Europe/Paris
collections:
  photo_gallery:
    title: Photo Gallery
    output: true
  photo_spectacles:
    title: Photos Spectacles
    output: true
  posts:
    title: Posts
    output: true
  spectacles:
    title: Spectacles
    output: true
  uploads:
    title: Uploads
    output: true
  presentations:
    title: Presentations
    output: true

defaults:
  - scope:
      path: ""
      type: spectacles
    values:
      layout: fiche
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentation
