# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

baseurl: "compagnie-jtembrasse"
timezone: Europe/Paris

# Name of website
title: Compagnie Jtembrasse

# Your name to show in the footer
author: Céline Creates

# The keywords to associate with your website, for SEO purposes
#keywords: "compagnie,jtembrasse,theatre"

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: spectacles
    values:
      layout: fiche
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentation

collections:
  photo_gallery:
    title: Photo Gallery
    output: true
  photo_spectacles:
    title: Photos Spectacles
    output: true
  posts:
    output: true
  presentations:
    title: Presentations
    output: true
  spectacles:
    title: Spectacles
    output: true
  uploads:
    title: Uploads
    output: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
