---
title: Compagnie Jtembrasse
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  spectacles:
    title: Spectacles
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: spectacles
  values:
    layout: fiche
- scope:
    path: ''
  values:
    layout: default
